### ISSUE TITLE
more flexible method of specifying CASTRO_HOME is needed

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#112]
Currently, we specify `CASTRO_HOME` in problem make files using a relative path, like
```
CASTRO_HOME = ../../../
```
This ensures that when we compile a problem, it is using the source that our problem directory lives in.

This also ensures that the test suite works, because regardless of what `CASTRO_HOME` might be set in a `.bashrc`, the Castro source for the problem is used.

If we instead did 
```
CASTRO_HOME ?= ../../../
```
we should not guarantee this.

However, the current method restricts the flexibility of the build process. 

@maxpkatz can you expand your use case for wanting to change this?

**Comment by maxpkatz** [comment]
The use case is that if I want to build a problem in the Castro/Exec/ directory as of now, I have two options -- either (a) copy the source code to a separate location and build there, or (b) build the executable in the root file location inside Castro and then copy the executable elsewhere.

(a) is suboptimal because it results in a bunch of different copies of the source code floating around, which can easily get out of sync from thr main repo. (b) is suboptimal because it means I can only have one build of the executable at a time, and if I want to update any one of my local problem directories I need to go back to Castro, do a make clean, possibly check out a different commit, and then build again. This would be avoided if I could have built the problem in a separate directory, because then I would not have to destroy the copy of the executable in that place to update it in another place.

So I prefer being able to write a makefile that can just do an include of the main makefile in Castro. This way I can maintain multiple builds in separate places while not being required to make sticky copies of the source code to each place.

**Comment by zingale** [comment]
Working on this is the `makesystem` branch.

The use case is the following: let's say we want to build in some random directory.  It would be nice to be able to simply copy the problem's `GNUmakefile` and then go.

**Comment by zingale** [comment]
the test suite now defines `CASTRO_HOME` always, so this is not a testing issue anymore
