### ISSUE TITLE
source terms for hydro prediction are not properly ghost cell filled

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#116]
in `construct_hydro_source`, there are a number of places where we do a `FillBoundary()`, for sources that will be used, for example, in tracing during the reconstruction:

```
    sources_for_hydro.FillBoundary(geom.periodicity())
    dSdt_new.FillBoundary(geom.periodicity());
```

But `FillBoundary` does not work for physical boundaries nor for coarse-fine interfaces.

We need to do a real fill here.

**Comment by zingale** [comment]
I think we can use `FillDomainBoundary` here, and `FillPatchUtil`

**Comment by zingale** [comment]
@WeiqunZhang is there a tutorial example that shows how we can properly fill the ghost cells for `sources_for_hydro` in `Castro::construct_hydro_source` in `Castro_hydro.cpp`?

This is not `StateData`.

**Comment by WeiqunZhang** [comment]
Maybe a simple extrapolation is good enough.  To do something similar to fillpatch, we need to fill the physical boundaries.  So how do we do that?  We also need to interpolate from coarse in space and time.  To interpolate in time, we need the coarse level to have `sources_for_hydro` at the beginning and the end of the timestep.  So that means it is essentially a `StateData`.

**Comment by zingale** [comment]
okay.  I think we should make it `StateData`.  Need to remind myself why we have dS/dt as `StateData` currently.

One thing we should do is have a separate `NSOURCES` variable, which is `NVAR - NSPEC`, and use that for the size, since we don't really have a use case for species sources in the Strang integrator.  We could make this an option.

**Comment by zingale** [comment]
alternately... it might be possible to fill the ghost cells explicitly in the source construction by looping over them and initializing them from the `State_Type` MF

**Comment by zingale** [comment]
#165 will help with making this into `StateData`

**Comment by maxpkatz** [comment]
dS/dt is StateData for basically this same reason, that I didn't want to have to worry about explicitly doing ghost zone or domain boundary fills. However, it has the flaw from #154 where sometimes users override the normal fill. It was also done to preserve the predictor value on a restart. sources_for_hydro doesn't need to be saved after a timestep is done which is one reason why I did not make it StateData.

**Comment by maxpkatz** [comment]
I should note though that the checkpoint issue is not a reason to avoid making it StateData. Any individual StateData can be easily excluded from being saved in the checkpoint.

**Comment by maxpkatz** [comment]
We should solve both by making a subroutine ca_genericfill which we'll use for all the pieces of algorithms that users should never need to adjust. ca_genericfill will just call filcc and do first-order extrapolation (or reflecting extrapolation where appropriate at symmetry boundaries).

**Comment by zingale** [comment]
agreed! that's a good idea.

**Comment by zingale** [comment]
this would be best with the idea of squashing all of the sources into a single MF -- I think you have a branch for that.

**Comment by maxpkatz** [comment]
That issue is gated by me needing to figure out how to rewrite wdmerger without depending on the individual sources. But for this one and #154 we can go ahead and do this immediately.

**Comment by maxpkatz** [comment]
We have an opportunity here to clean up the code a bit. Suppose we do #165 as proposed by @zingale as a way to simplify this. If we didn't have the lagged source term predictor, then at this point we could just replace the sources_for_hydro entirely with the old_sources, and promote old_sources to StateData.

The source term predictor's existence means that we cannot do this; we still need the temporary MultiFab. But it also means we need to store new-time StateData. (This is not the default yet, but it will be, so this extra memory usage will be the default.) Also by default we're storing new-time source data anyway until the end of the timestep, so that we can recompute the sources after a reflux. So, we can simplify all this by just co-opting the Source_Type StateData, to have both old and new data, and have it be the actual sources rather than their time derivative. 

Then when we want the sources for the hydro, we can just FillPatch from the old-time sources StateData into sources_for_hydro. To capture the effect of the source term predictor, then before we compute the old-time sources, we can compute the derivative from the last step using both the old and new data, divided by dt from the last step. This would be done just prior to the time-level swap in initialize_advance. Then we can store this derivative in sources_for_hydro, and add the old-time sources to it later.

**Comment by zingale** [comment]
this is fixed now
