### ISSUE TITLE
restarting a checkpoint with a new binary

### ISSUE THREAD

**Issue by dkhatami** [AMReX-Astro/Castro#123]
I'm trying to figure out the best way to restart a checkpoint using a different binary with new physics. That is, I want to run the first part of the simulation using hydro only, and then take that checkpoint and run the simulation with a new binary that includes radiation. So this would also include some way to initialize the radiation field on restart as well. The case I'm interested in is to just set the radiation temperature equal to the gas temperature.

**Comment by zingale** [comment]
is this something that is still needed?

**Comment by maxpkatz** [comment]
Even if it is, I see no way to do it given the way the code is written, at least in the general case. Our only recommendation here can be to start your first simulation with all of the physics you need but turn off the actual updates/advances in the code using the appropriate inputs parameters, so that the field is zero until you need it.

It should be straightforward to have a flag to (re-)initialize the entire radiation field on a restart.

**Comment by zingale** [comment]
closing as "wontfix" for now.
