### ISSUE TITLE
ca_denfill is used for things other than density

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#154]
In particular, it seems that `ca_denfill` is used for `Source_Type`, `SDC_Source_Type`, `SDC_React_Type`

This can be a problem, since some code with inflow / external boundaries takes specific actions for the density.  For example, the HSE BCs

**Comment by maxpkatz** [comment]
It is also the case that denfill is used when filling boundaries for derived data that need a ghost zone (e.g. divu) so it's still not safe for denfill to actually assume density. We should stop calling it denfill and make it generic for any state component.

**Comment by zingale** [comment]
I don't think this is true anymore.  Can we close this?

**Comment by maxpkatz** [comment]
This is still a problem with `ext_denfill`. Despite the name, this routine is not called on only the density; it's called whenever we need a single component of the state. In practice in Castro, this will happen when we use `AmrLevel::derive()` to make a copy of a particular state variable, and if that is not the density, then `ext_denfill` is not right. Fortunately this is not a very serious problem because in the `derive()` cases I can think of (tagging and diagnostics) we don't end up using the ghost zones.

**Comment by maxpkatz** [comment]
We're also making this mistake with the option `fill_ambient_bc`.

**Comment by zingale** [comment]
this is now fixed in #1356.
