### ISSUE TITLE
rotating_torus has lots of Riemann errors

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#1645]
In the first steps of the `rotating_torus` problem we get lots of warnings from the Riemann solver:

```
WARNING: (rho e)_r < 0 or pr < small_pres in Riemann: -1.590857916e-11 1.610360901e-15 1e-200
```

**Comment by zingale** [comment]
This happens right at the first Riemann solve, so this is not due to the transverse corrections.  It seem like the data is so discontinuous in (rho e) that we are generating a negative interface value of (rho e), so maybe the warning is doing the right thing?

Still need to check if it is due to any source terms.

**Comment by maxpkatz** [comment]
This is definitely due to the source terms. I have observed this now in multiple problems with self-gravity (but not any problems without gravity). For example you can see it in 1D DustCollapse. In particular you can see this even in the inner part of the domain where the density is initially large and uniform, with zero velocity. At t = 0, there is no velocity on the grid, and in the PPM the velocity jump is entirely dominated by the gravity source term. But the velocity jump has a contribution to the edge state for density and internal energy in the PPM scheme, and that is creating extreme values. In the 1D DustCollapse setup we have uniform rho = 10^9, but edge states that have densities of 1e12 and -1e12 (which then gets floored to 1e-6).

**Comment by zingale** [comment]
this is likely related to #1599

**Comment by maxpkatz** [comment]
Sketching out when we should expect this to be a problem: when there is uniform pressure and density, the alpha term goes as du * rho_ref / cs_ref, and when we are initially at rest (or at uniform velocity) du is dt * I_src / 2. So if we compare the ratio of this alpha term to rho_ref, we should expect it to cause a problem when it is of the same order of magnitude as rho_ref, which means dt * I_src / cs_ref ~ 1. This means we should expect it to be more likely to be a problem either when g is large or when dt is large. Since dt ~ dx / cs for hydro, this means we would also expect it to occur more preferentially at low resolution. This is consistent with my observation that I can make it go away with a *very* restrictive init_shrink -- for the giant impact setup, merely choosing 0.01 didn't do anything, but using 1e-6 did. This makes sense to me now, because the value I'd have to choose would need to be small enough to make the g term "small," which will be problem dependent and could be arbitrarily small for a given resolution.

**Comment by zingale** [comment]
could we take the approach that if rho < rho_cutoff, then we don't care about the dynamics and not trace the source term in that cell?

**Comment by maxpkatz** [comment]
It depends on whether rho_cutoff is scaled to rho. Based on my observation above, we could expect this in some cases to cause large swings in the integral of rho, and while in many cases this will cause a rho < small_dens, there could be other cases where it causes a big change in rho but not big enough to trigger a floor, for example, and we would still consider that an ill-posed problem. But possibly it could work if it is something like "the source term cannot cause the edge state to be too different from the reference state in relative terms."

Another note: while the warnings only started with #1618, I assume we've had this problem for a while, and only just recently realized it.

**Comment by zingale** [comment]
yes, the problems were most certainly there all along

I think that the Nyx fix addresses the *the source term cannot cause the edge state to be too different from the reference state in relative terms* bit

**Comment by maxpkatz** [comment]
I think it does something different than that.

https://github.com/AMReX-Astro/Nyx/blob/563fb6618a8cc1ecdefa000d1ec7f2a746bdab2c/Source/Hydro/trace_ppm.cpp#L345-L367

If I'm reading this correctly, I think the nature of this change was that for the waves moving away from the interface, you'd end up not having the source term contribute at all, and this change makes it so that the source term always contributes to the update regardless of which direction the wave is moving.

**Comment by maxpkatz** [comment]
I think what's interesting about that change is that you'll always have both a positive term and a negative term of the same magnitude ~dt * g / cs going into the edge state for rho, which would always approximately cancel when you add alpham and alphap. So it's an interesting idea, but one thing we're noticing here is that this causes badness in both rho and pressure/energy, so if we wanted to replicate that (I'm not sure yet, I will think more about it) we should do it for pressure too.

**Comment by maxpkatz** [comment]
After some internal discussion we think that including the effects of the source terms is likely to be an interesting idea that is consistent with the current scheme for the characteristic projection. There is a separate question of whether it is even correct to do an integral of the source term under the parabolic profile (as we do, based on the discussion in Colella and Woodward), but we can address them separately.

**Comment by maxpkatz** [comment]
#1725 addresses the issue of the source terms in the reference state. This appears to fix the issue in several problems including DustCollapse.

It turns out the problem with rotating_torus is separate and is caused by the transverse fluxes causing (rho e) to go negative. So we'll have to deal with that some other way. The runtime parameter `castro.transverse_reset_rhoe=1` does work around this problem, but we should use this as an opportunity to re-evaluate whether we are doing (rho e) correctly in general in the transverse flux correction.

**Comment by zingale** [comment]
these errors appear to be gone now:
http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2021-06-25/rotating_torus.run.out

**Comment by zingale** [comment]
is this still an issue?

**Comment by zingale** [comment]
this appears to have been addressed.
