### ISSUE TITLE
does Reactions_Type really need 4 ghost cells?

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#1693]
It is not clear why Reactions_Type needs so many ghost cells.

**Comment by maxpkatz** [comment]
This was done in #863. The logic at the time was that we were doing the load balancing based on the previous burn, and since we burn on the ghost zones in addition to the valid zones, we would want to have data on the weights for the load balancing in the ghost zones too. But we are no longer doing that, and in any case even if we did, in retrospect we could have done an estimation using the valid zones only. So I agree we could set it back to 0 now.

**Comment by zingale** [comment]
There are a few issues here:

* We burn on Sborder in the first half of Strang.  We store the burn data in the Reactions_Type StateData and then after the burn, we apply it to the state.
* If we want to do a 4th order burn, we will need the ghost cells

**Comment by zingale** [comment]
I wonder if we can get away with just a single time-level of Reactions_Type -- do we need both the old and new time?

**Comment by maxpkatz** [comment]
We don't need Reactions_Type at all. As we discussed it's only relevant for plotfile data at this time.

**Comment by zingale** [comment]
We also rely on this for `reactions_max_solve_level`

**Comment by zingale** [comment]
this is done in #1770
