### ISSUE TITLE
Need to fill in chemical potentials to zones for solving nse state

### ISSUE THREAD

**Issue by zhichen3** [AMReX-Astro/Castro#2347]
We need to pass in the chemical potentials for neutrons and protons for solving the nse state in each zone effectively.

**Comment by zingale** [comment]
There are a few ways we can do this.

We probably want to add `mu_p` and `mu_n` to the data carried in each zone.  If we only need this for the burner, then I think we can just add it to the conserved state and not worry about advecting it or anything, since it is just going to be used as an initial guess.

That would mean adding two lines to `Source/driver/_variables`

The question is -- do we bother to initialize it in all cases? or only for zones that went into NSE?

**Comment by zingale** [comment]
Just to be clear -- we only want to carry these as an initial guess for the NSE solver to accelerate the solve.

**Comment by zingale** [comment]
Alternately, we could just make a new StateData for this that is only defined if we are doing NSE_NET and then we only allocate a single time level.

**Comment by zhichen3** [comment]
If we don't have the initial guess, the solver might just fail to solve. I think we need them in all cases because how do we know if the zone goes to NSE without solving for NSE?

**Comment by zingale** [comment]
okay, so I think that it is best to do this then as separate StateData, that way we don't incur added memory in the fluxes.

**Comment by zhichen3** [comment]
closed by pr #2354
