### ISSUE TITLE
migrate test suites to groot

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#246]
We should move the nightly test suites from `bender` to `groot` and reconfigure them to run in less wallclock time.

**Comment by maxpkatz** [comment]
I believe for most tests one step is sufficient, and would actually helpful because we can tell if changes are roundoff level are larger. For the tests with hundreds of steps, it's difficult to tell from the end point whether the results are a non-trivial effect or just the summation of many roundoff-level changes.

One catch is that for certain cheap tests in 1D or 2D, say, it's easy to verify no changes by just checking that the code reaches the exact same stopping time. This trick would be unavailable if we made every test take only one step, so I'd say let's only make the change for the expensive tests.

**Comment by zingale** [comment]
the problem is that 1 step means that we never refine.  I like to trigger refinement and grid movement.

**Comment by maxpkatz** [comment]
A single step will still trigger refinement for the tests that satisfy the criterion at initialization, so in those cases we can do it.

**Comment by zingale** [comment]
the migration should be done now.  Tests will take 1.5 hours.  We can further refine things, but it is _much_ fasterer than before.
