### ISSUE TITLE
output where and why the timestep limit is set

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#328]
We should have an option to print out where in the domain is the most restrictive timestep and what limiter is the cause (hydro, diffusion, reaction, ...)

**Comment by maxpkatz** [comment]
We already print out which limiter is controlling the timestep, so this is half done already :-)

**Comment by zingale** [comment]
it doesn't seem that we separate the diffusion timestep from the hydro timestep.  It would be nice to know which of these is at fault.

**Comment by maxpkatz** [comment]
That is true.

I'll note that since we already perform two AllReduce calls to get both the hydro and reactions limited timesteps, and doing one for diffusion would add a third, we could combine these into a single ReduceRealMin and just do the minimum over all three at once (Weiqun added at some point the ability to hand initializer lists to the ParallelDescriptor routines).

**Comment by maxpkatz** [comment]
Seems like MPI_MINLOC (https://www.mpi-forum.org/docs/mpi-1.1/mpi-11-html/node79.html) could be useful for the location information.
