### ISSUE TITLE
generic_fill doesn't handle external boundaries

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#409]
the generic_fill routine, which is used, e.g., for sources, does not handle external boundaries.

**Comment by maxpkatz** [comment]
I'm not sure there's a bug here. It's true that the generic fills don't deal with external BCs, but for the source terms we replace EXT_DIR with FOEXTRAP. That may not always be a great choice -- maybe there's some clever way we can implement the source term BCs in terms of the state BCs.

One thing this made me realize is that it's safer to put the EXT_DIR -> FOEXTRAP replacement inside generic_multifill rather than in Castro_setup.cpp, in case we use that routine later but forget to make the same change for that new StateData. So I'll assign myself for that. Is there anything else to do here?

**Comment by zingale** [comment]
I agree -- this is the safest thing to do.

**Comment by zingale** [comment]
note, I just did this same change for source_fill, so I can do it for generic fill on PR #635

**Comment by zingale** [comment]
okay.. this is done as part of that PR now.

**Comment by zingale** [comment]
The same will be done for source_fill.  Since I closed #635, I'll do this on another PR
