### ISSUE TITLE
Hi! bugs@ $CASTRO_HOME/Exe/hydrotest/ ? Have you ever met them?

### ISSUE THREAD

**Issue by xumustc** [AMReX-Astro/Castro#413]
Hi! 
bugs@ $CASTRO_HOME/Exe/hydro_tests/ ? 

1. double_bubble/README:'contour2.py can be found in the AmrProcessing directory'. Actually no contour2.py. 

2. double_bubble and gamma_law_bubble both run with error reported,such as 'amrex::Abort::10::State has NaNs in the density component :: check_for_nan()!!!'

3. HC_bubble runs with such error:'$AMREX_HOME/Src/Base/AMReX_BLProfiler.cpp:1473:37:error:invalid conversion from ?.onst MPI_Status*? to ?. PI_Status*?[-fpermissive]...BL_MPI_REQUIRE(MPI_Get_Count,&status,MPI_UNSIGNED_CHAR,&c000)

Have you ever met them?
Thank so much for reviewing the above!

**Comment by WeiqunZhang** [comment]
For number 3, MPI standard has changed since MPI-3.  More specially, `MPI_Get_count` has changed from `int MPI_Get_count(MPI_Status *status, ...` to `int MPI_Get_count( const MPI_Status *status, ...)`.  Unfortunately we usually use MPI-3. 

You can choose one of the following options.

(1) Just wait for a couple of days.  AMReX developement branch has a fix for this.  It will be merged to master on Oct. 1, 2018.

(2) Use AMReX development.

(3) Do not use profiling.

(4) Upgrade MPI on your machine.

**Comment by zingale** [comment]
The `contour2.py` script can now be found at

https://github.com/AMReX-Astro/python-scripts

Note: it is suggested that you instead use `yt` for visualization.

**Comment by xumustc** [comment]
Thanks all of you for reply!
