### ISSUE TITLE
rad_sphere diagnostic gives the wrong answer

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#582]
If I run the C++ rad_sphere diagnostic on the RadSphere problem, I get a plot that look like this:

![radsphere](https://user-images.githubusercontent.com/7817509/55297494-8f21e680-53f4-11e9-90f8-318ef91f7006.png)

It is almost like it is being computed at the wrong position.  The Fortran version of the diagnostic (that is no longer part of Castro) gives the proper solution.  

I am running the tool as:

```
./rad_sphere.ex -p plt01001 -r 0.06 -g group_structure.dat
```

**Comment by zingale** [comment]
@harpolea maybe we can look at this together?

**Comment by harpolea** [comment]
I think it's due to how I'm converting between 2d Fortran arrays and 1d C++ vectors - `vars_bin` is indexed differently here https://github.com/AMReX-Astro/Castro/blob/f23c5f8e6c3f36e25d797a0d1a4566a8e3077237/Diagnostics/Radiation/rad_sphere.cpp#L224-L228 and here https://github.com/AMReX-Astro/Castro/blob/f23c5f8e6c3f36e25d797a0d1a4566a8e3077237/Diagnostics/Radiation/rad_sphere.cpp#L245-L249
For the example I'm running it doesn't seem to be doing anything stupid, which makes me suspect it may be the former which is at fault here.

**Comment by harpolea** [comment]
I may have fixed it in f7b18025 - @zingale would you be able to run again and see if it works now?

**Comment by zingale** [comment]
this is fixed in 07e5b29e
