### ISSUE TITLE
GPU performance regression

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#730]
Running the 3-d flame_wave problem on groot using AMReX 20.01, Microphysics 20.01 shows a slowdown in Castro of 10% between 2019-12-26 and 2020-01-01.  This can be seen with the following Castro hashes:

slow: `1604f107479a2b1d3a99d9da86ec8662b440ecb4`
build as:
```
module load gcc/7.3
make COMP=pgi CUDA_ARCH=70 COMPILE_CUDA_PATH=/usr/local/cuda-10.2 USE_CUDA=TRUE TINY_PROFILE=TRUE NETWORK_DIR=iso7 DIM=3 DEBUG=FALSE USE_ACC=FALSE USE_MPI=FALSE USE_OMP=FALSE -j 20
```
run as:
```
./Castro3d.pgi.TPROF.CUDA.ex inputs_3d.testsuite.gpu  amr.checkpoint_files_output=0
```

it will report it takes ~456 s.

Now checkout `78650e711cb19af67032140d19278f0e042ba03f` and repeat and it will say it takes ~404 s.

**Comment by zingale** [comment]
Using `git bisect`, it seems that the commit that is responsible for most of the slowdown is this:
```
commit 2893f20dbf99689f026fdef2a4cc2e1a5a042a89
Author: Max Katz <maxpkatz@gmail.com>
Date:   Sat Dec 28 03:44:12 2019 -0800

    Effectively disable tiling when using CUDA
```

Oversubscription on this problem may complicate things.

**Comment by maxpkatz** [comment]
Right, this is fundamentally linked with oversubscription. The CTU hydro has rudimentary logic that prevents us from running too many boxes at the same time when we are oversubscribed, and tiling increases the number of boxes which meant that this limiter kicked in sooner and helped out performance a little bit. Disabling tiling sped up the normal case a bit but slows down the oversubscription case because now there's more memory fighting for space on the GPU at the same time.

While I don't want to spend a lot of time on this case, in bb03878a I came up with another simple heuristic where we also prefetch data in and out of the GPU if we're oversubscribing. This recovers the performance we previously had, plus a little more. A coherent, smart approach to this is still lacking, but this is at least a bandage that keeps us moving in the right direction.
