### ISSUE TITLE
update quick start instructions on webpage

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#777]
We should update the webpage:

https://amrex-astro.github.io/Castro/

to reflect the submodule workflow.

**Comment by maxpkatz** [comment]
Perhaps we should also suggest that when they get started with the Sedov case they should do `USE_MPI = FALSE` (since not everyone will have an MPI setup on their laptop, say) and `DIM=1` (so that it runs quickly). Also, we need to fix the path since it's now in Exec/hydro_tests.

Finally, in the visualize section, since this is a 1D test perhaps we can demonstrate a quick workflow using `fextract` to get the raw data and then gnuplot or numpy to plot the data.

**Comment by zingale** [comment]
I was actually thinking of making yt the main focus of the visualization section, since it seems to be what we all use.

**Comment by maxpkatz** [comment]
I'm happy to show that, and I think it's a great idea.

My thinking is that when I download someone else's code for the first time, I want a really easy way to run it and verify that it worked correctly. yt takes a little time to set up and I want to decrease barriers to entry for new users, so at least one use case not using it seems like a good idea to me.

**Comment by zingale** [comment]
okay, sounds good.

**Comment by zingale** [comment]
this has been updated. 

Will make a separate issue about vis docs
